### PR TITLE
test: set cwd based on ESLint directory

### LINKED ISSUE #13: Question: Error: Cannot find module '/package.json'
Hi,

Very excited to have this tool available. Thanks so much!

## Issue Type

Question

## Issue Description

I don't know if you'd consider this a bug, but wondering if you might know how to resolve, being more familiar with the Atom environment.

In my linting config (`eslint-config-ash-nazg`), I dynamically detect the `ecmaVersion` and `env` for my `.eslintrc.cjs` based on the minimum version of the `node` subfield of `package.json` `engines` so as to avoid the need for manually setting them.

With this code, I was using `process.cwd()` (`process.cwd()` helps the code work from the command line) to try to find the project root (and then `package.json` within that), but the base path it returns is `/`. I then tried the following:

```js
typeof atom === 'undefined'
              ? process.cwd()
              : (atom?.workspace?.getCenter()?.paneContainer?.activePane?.activeItem?.getDirectoryPath() || process.cwd())
```

But the path is apparently not being found (same result if I remove the optional chaining operators). This code, even with the atom-specific code, appears to still be returning `/`.

Any idea if it is possible for me to detect (or for you to set any properties I can detect) the root directory of the current file's project?

I am using pnpm, which can theoretically change path discovery, but I wouldn't think that would affect Atom's discovery.

Thanks!

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint-node` does not
- [x] Paste the output of the `Linter Eslint Node: Debug` command from the Command Palette below

```
Linter Eslint Node: Debug output here

Cannot read config file: /Users/brett/eslint-config-ash-nazg/rc.js Error: Cannot find module '/package.json' Require stack:

/Users/brett/eslint-config-ash-nazg/rc.js
/Users/brett/jsdoccomment/node_modules/.pnpm/@eslint+eslintrc@[1]().2.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.[0]()/node_modules/eslint/lib/cli-engine/cli-engine.js
[/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0](mailto:/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0)/node_modules/eslint/lib/eslint/eslint.js
[/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0](mailto:/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0)/node_modules/eslint/lib/eslint/index.js
[/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0](mailto:/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0)/node_modules/eslint/lib/api.js
[/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0](mailto:/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0)/node_modules/eslint/lib/api.js Referenced from: /Users/brett/eslint-config-ash-nazg/sauron-node-overrides.js
linter-eslint-node debug information

Atom version: 1.60.0
linter-eslint-node version: 1.0.3
Worker using Node at path: /Users/brett/.nvm/versions/node/v14.17.1/bin/node
Worker Node version: v14.17.1
Worker PID: 81288
ESLint version: 8.11.0
ESLint location: [/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0](mailto:/Users/brett/jsdoccomment/node_modules/.pnpm/eslint@8.11.0)/node_modules/eslint/
Linting in this project performed by: linter-eslint-node
Hours since last Atom restart: 0.1
Platform: darwin
Current file's scopes: [
  "source.js"
]
linter-eslint-node configuration: {
  "disabling": {
    "disableWhenNoEslintConfig": false,
    "rulesToSilenceWhileTyping": []
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic",
    "source.ts"
  ],
  "nodeBin": "node",
  "warnAboutOldEslint": true,
  "autofix": {
    "fixOnSave": false,
    "rulesToDisableWhileFixing": [],
    "ignoreFixableRulesWhileTyping": false
  },
  "advanced": {
    "disableEslintIgnore": false,
    "showRuleIdInMessage": true,
    "useCache": true
  }
}
```

### PR DESCRIPTION
**Pull request by brettz9**
test: set cwd based on ESLint directory; fixes #13

### CODE REVIEW

**Review by UziTech — APPROVED** [review]
LGTM

**Comment by savetheclocktower** [comment]
I’m on a quick vacation, but I’ll take a look at this over the weekend.

**Comment by savetheclocktower** [comment]
Thanks for this.

I had one hangup here: the `process.chdir` call _into_ the new CWD is happening inside `getESLint` in a code path that won't get hit if we're reusing a cached instance. So it wouldn't be hard to encounter a scenario where the directory doesn't get changed.

Whether that matters depends on when ESLint actually consults `.eslintrc.js`. I would've bet $5 that it happened upon instantiation, and that we'd only need to change CWD long enough to create our `ESLint` instances. But I did some testing, and I'm wrong: if I put a logging message in that `.eslintrc.js` fixture, I can see that it isn't actually evaluated until a specific linting task is performed.

So we don't need to `chdir` _at all_ during instantiation; we just need to `chdir` before and after a linting/fixing job. I decided to move it above where we handle `debug` jobs just in case we ever decide to do anything CWD-dependent as part of a debug.

Dynamic behavior in `.eslintrc.js` gives me the willies, but I've got no legitimate argument against it; it works in the `eslint` CLI, after all. I'd hoped the `cwd` option in the `ESLint` constructor would behave identically in all respects and I wouldn't have to deal with `process.chdir` at all, but them's the breaks.

**Comment by savetheclocktower** [comment]
The CI failure on Windows cannot possibly be related to this change, so I'm going to land this PR later today. If it ever fails again I'll do whatever I need to to make it un-flaky.

**Review by UziTech — APPROVED** [review]

**Pull request merged**
